### PR TITLE
1.4.8 Chinese

### PR DESCRIPTION
**Pull request by 745275633**

### CODE REVIEW

**Comment by 745275633** [comment]
Chinese haven't upcase or downcase, so if you changed case, needn't change in Chinese.

**Comment by Yousei9** [comment]
For consistency I changed the drop down description in German and Chinese to match the actual drop down options.
These will only be translated if I translate the drop down itself, which would make telling users "set message level to "Errors & Warnings" difficult as they see totally different text.

**Comment by 745275633** [comment]
Maybe include both of them?

**Comment by Yousei9** [comment]
Sorry, I don't see the point in translating settings that are displayed in English when there's a description to that setting literally next to it.

**Comment by 745275633** [comment]
So what's your meaning?

**Comment by Yousei9** [comment]
I mean you don't translate text that remains the same regardless of used locale.

**Comment by 745275633** [comment]
But why not both of them

**Comment by Yousei9** [comment]
Because it's silly to write "Off (OFF): turns the thing off."

**Comment by 745275633** [comment]
just 98407ba ? I don't think it't good.

**Comment by Yousei9** [comment]
I think that's good enough.
It's also exactly what I had except for a lack of whitespaces after colons.

**Comment by 745275633** [comment]
Oh, You can delete spaces because colons if full-width

**Pull request closed without merging**
