### PR TITLE
orders processed in order of priority

### PR DESCRIPTION
**Pull request by NiftyManiac**
The bug I described here: https://forums.factorio.com/viewtopic.php?f=97&t=36976&start=220#p244019

Orders should be processed and dispatched in order of priority.

### CODE REVIEW

**Comment by Yousei9** [comment]
I guess you misunderstood what Provider Priority does.  Provider Priority only makes orders prefer picking up items from higher ranking providers.
It was added to deal with waste items from Bobs mods, not to skip in line for round robin.

Orders themselves are sorted only by time for round robin. 
How would you even set an order priority in the first place? 
Derive it from provider priority? Makes no sense as orders are triggered by requests.
Add a Requester Priority? Would break round robin for sure and make trains queue up in front of high priority requesters, especially with Best Effort on.

**Comment by NiftyManiac** [comment]
It seems to me that _requests_ (multiple items desired at a station) are scheduled on a round-robin basis, but _orders_ (one-to-one station transfer) are not. I'm not touching the round-robin scheduling of requests at all. If I understand it correctly, the current behavior when processing a single request is:

- Separate it into multiple orders, one per item
- Try to merge orders if several come from the same place
- Try to find trains for as many orders as possible
- Skip every order that doesn't have a suitable train

The problem is that if a single train is suitable for multiple orders, which order it receives is a) always the same, and b) undefined, because it's based on the order of a table. I'm not trying to do round-robin for orders. I'm just making the behavior defined and consistent with station-choosing rules.

And even if you don't like my strategy for whatever reason, avoiding undefined behavior is worthwhile anyway.

**Comment by Yousei9** [comment]
The logic per tick is even simpler:
- generate one order per item aka find best provider for item
- merge orders
- find the best matching train
- handle the first order and push the requester to the end of the queue

It will generate one delivery every dispatcher_update_interval (default 1sec). It's rare to have a setup where you would constantly need more than one train/sec dispatched and it saves a lot of update time.

You're right that the items are decided by the generated item list. It's equivalent to filter inserters always setting their filter to the first 5 items in the item list when sending them more than 5 signals.

I don't see how sorting the orders with the same logic I sort providers would fix using the item list's order. It simply replaces that order by a much more arbitrary order of which provider happens to have less active deliveries and higher priority.
Again, to fix this undesired behavior you have to sort orders by tick the item was last sent.

**Comment by NiftyManiac** [comment]
With filter inserters it's clear: I can handle 5 items. If you give me more than 5 items, I'll pick 5, and they may not be ones you want. The GUI makes this limitation clear.

Here though, it's not clear to the user. If a station is set to request iron, we know where it'll go: the iron provider with the least activity, the highest priority, or the most items, in that order. If a station is set to request both iron and copper, we have no idea where it'll go! We only know that it'll go to the "best" iron station, or the "best" copper station. Even if the best copper station is way better by normal criteria than iron, it'll still decide on iron arbitrarily. It's opaque. I don't see why you think choosing the best station (using already established criteria for "best") is "much more arbitrary" than an order based on internal data representation (and one that could theoretically change with a new version of Lua).

Meh, we don't need to continue this argument if you feel strongly against it. I feel like the default behavior is a bug... but if you don't I'll just keep my own fork going, no harm done.

**Comment by Yousei9** [comment]
Perhaps it came out wrong. I never said it's not a bug.
What I said was, your proposed fix only works for some cases while some other remain unfixed and produce even less consistent behavior.
e.g. there is no high priority steel-plate provider while copper-plate and iron-plate have high priority providers. That would once again make iron and copper preferred over steel.

I also said what a clean permanent solution would have to include. Unless you want to tackle it yourself I'm going to put that on my todo list for the next feature release.

**Comment by NiftyManiac** [comment]
> e.g. there is no high priority steel-plate provider while copper-plate and iron-plate have high priority providers. That would once again make iron and copper preferred over steel.

Well, if I have high priority iron and copper stations... I'm hardly going to be mystified when the dispatcher prioritizes iron and copper! That's what priority is for, to break ties between equally-good stations. That's exactly how I'd expect setting priority to function. 

Plus, this method is flexible. If I want some more complex specific behavior (i.e., I want it to focus on pulling from a specific mine) I can change the priority via circuit without having to turn the station on/off. In fact, this is what I'm currently doing: I have 100 mines, I know which ones should be prioritized and to what degree, so I can manage it myself and the trains will visit the stations in order of priority. This is only possible with the changes I made.

I'm not a fan of the sort-by-tick idea; it's better than no sorting, but it's also opaque. You'd need to document it specifically, while I think setting priorities is already intuitive.

**Comment by Yousei9** [comment]
Being able to pull from specific mines would remain unchanged.
All that would/have to change is requested multiple item types would fill up more equally instead of sequentially (unless orders can be merged)
for my example above cycle 1: iron, cycle 2: copper, cycle 3: steel, cycle 4 iron, .... until all are full
currently it'll fill iron until full, copper until full, steel until full

How provider priority matters still eludes me.

**Pull request closed without merging**
